// import {} from "./lessons/lesson1_vars_types_cats.js"
// import {} from "./lessons/lesson2_arrays_objects_if.js"
// import {} from "./lessons/lesson3_loops.js"
// import {} from "./homeWorks/hw1.js"
// import {} from "./homeWorks/hw2.js"
// import {} from "./homeWorks/hw3/hw3add.js"
import {} from "./homeWorks/hw4-func/hw4-func.js"
